### ISSUE TITLE
PermissionError: output/Unknown

### ISSUE THREAD

**Issue by zachary523** [BtbN/FFmpeg-Builds#136]
I am very confused whats going on... Perhaps I'm stupid and I'm doing something wrong, But I did install ffmpeg and the fonts as well, So what is going on

Traceback (most recent call last):
  File "fnf_converter.py", line 543, in exportAsOsz
  File "site-packages\pydub\audio_segment.py", line 809, in export
  File "site-packages\pydub\utils.py", line 60, in _fd_or_path_or_tempfile
PermissionError: [Errno 13] Permission denied: 'output/Unknown - apparition/audio.mp3'

**Comment by BtbN** [comment]
That looks like Python just has no permissions to write where you told it to write to?
It doesn't look like ffmpeg is even involved in that, so not sure what to tell you.
