### ISSUE TITLE
"Probe 'native' using 'C:\PATH_Programs\bin\ffmpeg.exe' failed, trying fallback"

### ISSUE THREAD

**Issue by zbeb** [BtbN/FFmpeg-Builds#270]
Hey so I am trying to make a music discord bot, I installed ffmpeg from this site: https://github.com/BtbN/FFmpeg-Builds/releases

The 3 executables are located in this path:
C:\PATH_Programs\bin\ffmpeg.exe
but for some reason when I play music with the bot, it plays the music just fine but prints this as an error:

```
ERROR    discord.player Probe 'native' using 'C:\PATH_Programs\bin\ffmpeg.exe' failed, trying fallback
Traceback (most recent call last):
  File "C:\Users\zbeb\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\player.py", line 526, in probe
    codec, bitrate = await loop.run_in_executor(None, lambda: probefunc(source, executable))
  File "C:\Users\zbeb\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\zbeb\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\player.py", line 526, in <lambda>
    codec, bitrate = await loop.run_in_executor(None, lambda: probefunc(source, executable))
  File "C:\Users\zbeb\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\player.py", line 548, in _probe_codec_native
    output = subprocess.check_output(args, timeout=20)
  File "C:\Users\zbeb\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\zbeb\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\PATH_Programs\\bin\\ffmpeg.exe', '-v', 'quiet', '-print_format', 'json', '-show_streams', '-select_streams', 'a:0', 'https://rr7---sn-cxab5jvh-cg0ee.googlevideo.com/videoplayback?expire=1683886515&ei=U71dZJTxGZvMgAf6yquoBw&ip=2a02%3Aa03f%3A62f3%3A6900%3A15e4%3A8606%3A8b7d%3Afb1a&id=o-AKMZbaRiyco0e0vSbc2MDoxAtlJ7ypkvtnkQ-P4dD9qb&itag=249&source=youtube&requiressl=yes&mh=oa&mm=31%2C29&mn=sn-cxab5jvh-cg0ee%2Csn-25ge7nzz&ms=au%2Crdu&mv=m&mvi=7&pl=42&initcwndbps=1656250&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=R6oe-XE4iuAi__xpi4xkHbcN&gir=yes&clen=972808&dur=135.581&lmt=1649077799814946&mt=1683864552&fvip=5&keepalive=yes&fexp=24007246&c=WEB&txp=5532434&n=vtc2d8QBNdnjTQ&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgI0R65Ck8ad_gH2Rd4BKBqAjSuGrmcBcHWyIlvY-fMS0CIQC8wNGJjZVeSq_xanYGW2zyEByHHQ_s7qvZjJUo6SHVmw%3D%3D&sig=AOq0QJ8wRAIgKvSksVam7HX2QSyt-LuxrE4Ld-HLiNSq3SBTJW2qwH8CID4N0R1vddHAqgleoHS7p95SzN_q0qqdvYvovmSpfp3M']' returned non-zero exit status 1.
```

**Comment by BtbN** [comment]
That's an error in some python script, not ffmpeg.
All it's saying about ffmpeg is "there was some error".

You'll need to dig out the actual error ffmpeg is producing to get anywhere.

Very likely a case for ffmpeg-user or #ffmpeg, not this issue tracker.

**Comment by rokibhasansagar** [comment]
@zbeb
Probing is done by `ffprobe`, not `ffmpeg`.
The command line at the end clearly using arguments for `ffprobe`, but in `ffmpeg`.
It was bound to break.
Fix it in your Python script.
